### ISSUE TITLE
文件存储路径在数据库中的记录优化

### ISSUE THREAD

**Issue by jliu666** [skill6/skill6#118]
![image](https://user-images.githubusercontent.com/14869749/47506835-848e7e80-d8a3-11e8-8c39-ba9a9abff390.png)

**Comment by jliu666** [comment]
对数据库内测试数据的存储路径进行观察，发现路径存储为绝对路径，存在以下几个不适当的地方
1，后期文件服务需要分布式，此种方式已经不满足需求
2，文件路径分隔符没有归一
3，应当使用相对路径，后期可以统一迁移而无需修改数据库内容

**Comment by CrazyHusen** [comment]
已对齐，找时间优化

**Comment by CrazyHusen** [comment]
fix
合并在merge request #121 中
