### ISSUE TITLE
第三方授权登录联调

### ISSUE THREAD

**Issue by CrazyHusen** [skill6/skill6#129]
第三方授权登录后端已经开发完成，
TODO：
1、确认前端第三方授权登录方案
2、联调QQ和Github授权登录

**Comment by CrazyHusen** [comment]
研究了一下简书的CSDN的授权方案，设计技术流授权登录（其实对于登录通用）草案：

1. 点击登录，GET登录页面，后台记录当前页面至session，返回登录页面
1. 用户选择登录方式，如果是授权登录，则请求相应链接，并重定向到第三方授权界面
1. 授权完成回调接口，后端读取授权信息，成功后读取登录前页面并重定向

特别地，
1. 如果是手机、用户名或者邮箱登录，走相应流程，登录成功后直接在后台重定向至登录前页面，或者与第三方授权一样，回调某个接口实现重定向
1. 授权完成回调接口时，是否加个中间页面显示正在加载的图案提升界面友好性。如get页面返回加载界面，返回的页面再去post该请求，实现一边加载一边后端操作

**Comment by CrazyHusen** [comment]
关联merge #130

**Comment by Humsen** [comment]
推翻前面的方案，采用完全前后端分离的方式。后端只提供数据，前端实现权限和路由。后端shiro自定义实现session无状态化，如登录成功后返回角色和权限的json数据，由vue实现路由。后续也可直接扩展到app和小程序等应用。
