### ISSUE TITLE
此处类型正确吗?

### ISSUE THREAD

**Issue by jliu666** [skill6/skill6#64]
https://github.com/skill6/skill6/blob/4b31f76e4adbe031d336af4e2fda46055b6c4849/skill6-parent/skill6-website/src/main/java/cn/skill6/website/util/storage/BaseStoreHandler.java#L56

**Comment by jliu666** [comment]
这个地方设置的contenttype是认真的吗?还是忘记改了 :smile:

**Comment by CrazyHusen** [comment]
相当认真
