### ISSUE TITLE
对参数进行校验

### ISSUE THREAD

**Issue by CrazyHusen** [skill6/skill6#85]
是否需要在service类上面加一层校验类，有以下两个功能：

1. 对controller传过来的参数和以后的微服务调用参数进行校验

1. 对service返回的结果进行校验

1. 包装返回结果ResponseJson，不再在service中进行封装，践行“单一职责”设计思想

如有必要，有以下三种实现方式：

1. 在service上面加一层类，通过这些类调用service

1. 增加校验类，并在service实现每个函数前面先调用参数校验

1. **建议：通过注解实现，使用spring aop注解或者自定义注解**

**Comment by jliu666** [comment]
建议使用JSR 303对参数进行校验
